spring:
  application:
    name : "FullRestApi"

  datasource:
    url : "jdbc:postgresql://db:5432/postgres"
    username : "postgres"
    password : "changemeinprod!"

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

    hibernate:
      ddl-auto: create-drop

    show-sql:
      true

springdoc:
  swagger-ui:
    path: "/docs"